name: My first workflow

on:
  push:
    branches: [ "main" ]

jobs:
  image_build:
    runs-on: self-hosted
    steps:
    - name: checkout the code
      uses: actions/checkout@v4
    
    - name: login to docker repo
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/todoapp:v1
    
    - name: Push image to repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/todoapp:v1

  k8s-deploy:
    runs-on: self-hosted
    steps:
    - name: update deployment
      run: kubectl set image deployment/todoappdeployment todoappdeployment=${{ secrets.DOCKER_USERNAME }}/todoapp:v1
